### ISSUE TITLE
New firmware releases

### ISSUE THREAD

**Issue by karelpak1** [Paliverse/DualSense-List-of-Firmwares#4]
DualSense
https://fwupdater.dl.playstation.net/fwupdater/fwupdate0004/0x0520/FWUPDATE0004.bin

DualSense Edge
https://fwupdater.dl.playstation.net/fwupdater/fwupdate0044/0x0200/FWUPDATE0044.bin

**Comment by Paliverse** [comment]
Thanks, updated repo

**Comment by Paliverse** [comment]
There's also a new FW for DualSense but unable to find the correct URL to download the file, maybe you can look into it.

This is the json the PS Accessories app uses https://fwupdater.dl.playstation.net/fwupdater/info.json

**Comment by karelpak1** [comment]
Yeah, new firmware for Dualsense B
https://fwupdater.dl.playstation.net/fwupdater/fwupdate000B/0x0520/FWUPDATE000B.bin

**Comment by Paliverse** [comment]
weird, i tried basically the same link and didn't work, i guess i had it formatted wrong. Ill add it to the repo

**Comment by karelpak1** [comment]
It happens, feel free to close this issue.

**Comment by Paliverse** [comment]
Done.
